### PR TITLE
Added scoreboard manipulation in its current state to language docs, though I'm expecting to have to modify it when gnembon adds proper support for scoreboard manipulation in v1.7

### PR DESCRIPTION
**Pull request by Ghoulboy78**
I said it all

### CODE REVIEW

**Comment by gnembon** [comment]
Lol, is that to force me to add scoreboard API?

**Comment by Ghoulboy78** [comment]
more or less
also cos people can still work with the limited tools. It's like only having two pieces of wood to make a fire, so you need to get some pig entrails to serve as the string for a bow so you can make it the old fashioned way.
HEY! They should totally add pig entrails to the game so we can make better bows, lyres, and sacrifice them to get diamonds!

**Comment by Ghoulboy78** [comment]
(do you think I scared him off with that comment?)

**Comment by gnembon** [comment]
this should suffice
https://github.com/gnembon/fabric-carpet/commit/ba96b1b0343cb5a44db5c5608394dd3e38ce2270

**Comment by Ghoulboy78** [comment]
I LOVE U @gnembon ! U R DA BEST!

**Pull request closed without merging**
