### PR TITLE
Adding /script download

### LINKED ISSUE #713: Scarpet Request | /script get
## The Idea
I had an idea for a way for Carpet users to quickly and easily download and install scripts to their world.  An new choice for the `/script` command: `get`.

## The Implementation
`/script get` requires two arguments, a category and a name.  The category refers to the folders in the Scarpet Github repository and the name is the name of the desired script.  If the specified script exists, it will automatically be downloaded For example: the command `/script get survival angel_block.sc`  will download the `angel_block` script from the Scarpet repo and put it in the `scripts` folder for the current world, creating the folder if it doesn't already exist.  The command would only work for scripts in the repo to limit the chances for malicious use.

## The Challenges
The main sticking point with this suggestion would be the need to add some sort of web handler to access the Scarpet repo.
Additionally, I'm not sure if auto-complete would be possible without repeated queries to the repo.

### Special Thanks
Special thanks to Kollum in the Scicraft Discord for helping refine the idea when explaining it to them.

### PR DESCRIPTION
**Pull request by Ghoulboy78**
Very much a WIP thing, but a fun project nontheless
Resolves #713 

Tasks: 
- [x] Getting the actual code
- [x] Saving it to file properly
- [x] Proper suggestion/autocompletion
- [x] Testing saving to global folder on servers (Resolution: It doesn't work)
- [x] Adding detailed docs

### CODE REVIEW

**Comment by gnembon** [comment]
now tab completion ....

**Comment by Ghoulboy78** [comment]
Well first of all there is issue of actually getting it to get the correct code...

**Comment by Ghoulboy78** [comment]
That was just cos I wanted to quickly switch branches and fix the other ones... I don't like keeping stashed changes in case smth happens and I lose them.

**Comment by Ghoulboy78** [comment]
I also noticed this while researching: https://github.com/hub4j/github-api

**Comment by Ghoulboy78** [comment]
ok wtf? This is ridiculous. My IDE shows no errors, but this stupid thing does?

**Comment by Ghoulboy78** [comment]
oh wait, NOW it shows errors. Stupid piece of crap wouldn't respond for about a minute cos it was indexing.

**Comment by Ghoulboy78** [comment]
yo gnembon what's the deal with global carpet config scripts folder? like where does that get saved?

**Comment by Ghoulboy78** [comment]
Right now if it finds a file already in that location, it will throw an error and not do anything. But I thought about it and there is an interesting thought. Currently, survival/angel_block.sc would be put into a folder called survival, and in that would be created angel_block.sc. So it is unlikely that people who don't know what they're doing have put it there. Not to mention, that perhaps the file could have been updated since you last downloaded, in which case you could update? Idk it's just of commenting out a couple lines, but it changes quite a lot.

**Comment by gnembon** [comment]
you can put it even deeper, like /survival/angel_block would go into /config/carpet/scripts/appstore/surivival/angel_block.sc etc
And don't worry about updating, worry more about autocomplete

**Comment by Ghoulboy78** [comment]
ok, was just wondering cos it's like two lines of code, but potentially changing quite a bit, whereas the autocomplete is more of a coding challenge than a design challenge. The above issue is, as mentioned, like 2 lines literally.

**Comment by Ghoulboy78** [comment]
Admittedly my solution is kinda ugly, cos it basically reads the html response doc, and checks to see the tag which is used to store the file names in one long-ass regex Pattern object. It is vulnerable to breakage if github ever decides to redesign its web browser, so perhaps a better solution is needed, but I couldn't find it after quite a while of searching

**Comment by altrisi** [comment]
You could use Github API for suggestions, for example the `/repos/{owner}/{repo}/contents/{path}, as described in 
https://docs.github.com/en/rest/reference/repos#contents

**Comment by Ghoulboy78** [comment]
yeah, but that's all for javascript, not java. so idk, this seems to be the only option

**Comment by altrisi** [comment]
Ehhm... No?

Github API is http, it's just they also have a wrapper in JS for convenience.

**Comment by Ghoulboy78** [comment]
ah, so is there a way for me to manipulate in java?

**Comment by altrisi** [comment]
Yes, just call it like any other GET (web) request (I added an example URL to the comment above before seeing your last message)

**Comment by Ghoulboy78** [comment]
Ah thanks

**Comment by Ghoulboy78** [comment]
But wait @altrisi how do I read that?

**Comment by altrisi** [comment]
It's JSON, just pass the string to GSON.

**Comment by Ghoulboy78** [comment]
yeah I noticed, I was jsut having trouble cos I was an idiot and I tried to parse as JsonObject not JsonArray first

**Comment by altrisi** [comment]
I'd cache the suggestions in order not to reach ratelimiting (cache directories, then files for each directory when requested, not refreshed until at least 5-10 hours). Else it may cause increased network traffic and could stop working/ban the server's IP if someone abuses the suggestion provider, which IIRC would send the requests each time a single character changes.

**Comment by Ghoulboy78** [comment]
hmm, ye, that sounds like a smart idea.

**Comment by altrisi** [comment]
Maybe through guava's CacheBuilder, since it's already included in minecraft.

**Comment by Ghoulboy78** [comment]
hmm, I was thinking of a different solution which is basically to store the repo's files and stuff statically, so upon server creation (and restarts ofc), and then if the query throws an error it means that the repo's structure changed, so we just re-query and then resend. to the user the updated options. No caching, no nothing needed.

**Comment by Ghoulboy78** [comment]
yo @gnembon should I add an option to query from any repo or just scarpet one? cos the code is rather generalized so I think it may technically work on any repo, to in practice it's only been tested on scarpet for the time being

**Comment by Ghoulboy78** [comment]
Here is a video showcasing the suggestion thing working:https://www.youtube.com/watch?v=tQ3sAj6hYDI&list=PLAMmEWZKDdq4Xtl2aMyRfeVoZ5Zw7mV-6

**Comment by Ghoulboy78** [comment]
Ok, I've gotten the script downloading and saving to work, now I've got to test saving to the global scripts folder on a server, and it should be all good to merge. I'm not sure about whether the current docs are enough, perhaps you wanna add more?

**Comment by gnembon** [comment]
For what its setup to, works great. Its useless pretty much with local world location (primary use I guess)
Capture

Its a minor thing though, so if you don't see that in a few hours, I will just merge it and fix it myself.

**Comment by gnembon** [comment]
Capture
Also suggestions get pretty wonky. No pressure though - will fix it myself if you don't get that to work today.

**Comment by Ghoulboy78** [comment]
I do not see the issue with the global scripts folder. Weird. I did, however, fix the second issue, by simply not allowing a folder name to match the regex pattern : `\.+\.sc\`. Kind of a hack fix, I know, but also the only way I know to fix it tbh without getting too complicated. Also, I ensured that those two are the only types of names you could get, so it works ig.

**Pull request merged**
