### PR TITLE
Added 'sphere' iterator

### PR DESCRIPTION
**Pull request by Ghoulboy78**
I hope like hell it works

### CODE REVIEW

**Comment by Ghoulboy78** [comment]
you see, you said in discord that it would be nice if peeps submitted prs cos ur busy cos of some mysterious reason, so I just copy pastad code from `scan` command like literally underneath, then just edited so it worked. I hope it does now

**Comment by gnembon** [comment]
well, its not a sphere, its a ball. Second - its not really more efficient than running scan and adding that condition in the actual scarpet code. What would be nice is efficient sphere generator, similar to the one used in `/draw sphere` or other world edits. I don't think specific API call for balls is needed.

Having said that -there is one for diamond, mostly because of different method of iterating over an area. which makes it different. Lemme think about that. There is plenty shapes that would need to be covered and pollution built-ins space is not a good idea.

**Comment by Ghoulboy78** [comment]
um, ok. Ill try and add a diamond to the /draw command. You see, I was simply inspired by your comment to try and help, and sort of did things without thinking through.

**Comment by Ghoulboy78** [comment]
shall I close?

**Comment by Ghoulboy78** [comment]
also, @gnembon , wdym by

> What would be nice is efficient sphere generator, similar to the one used in /draw sphere or other world edits.

**Comment by Ghoulboy78** [comment]
couldn't you just you just use `/script fill (or outline) cx cy cz x1 y1 z1 x2 y2 z2 "x*x+y*y+z*z<=r*r" blue_stained_glass`, and then the same for other shape but instead with `/script run for(diamond(x,y,z,w,h),set(pos(_),'blue_stained_glass'))`
Unless you want a specific call for that in `/draw` command?

**Comment by Ghoulboy78** [comment]
actually this is useless

**Pull request closed without merging**
