### PR TITLE
hacky make carpet command permisison level configurable

### PR DESCRIPTION
**Pull request by adryd325**
quick and dirty way of making carpet command permission level configurable.

### CODE REVIEW

**Comment by gnembon** [comment]
why that would ever be useful?

**Comment by adryd325** [comment]
I have a creative server where "admins" are op level 4 and normal players are op level 2 (to have access to /gamemode, /tp, etc). I don't want normal players messing with the carpet config but i'd like op level 4 to still be able to.

**Comment by gnembon** [comment]
Ok, I get that. Well, settings.conf is writable by the /carpet command and your line will disappear so your method is very dirty.

You have to take care to write it back to the conf in case someone changes it. locked configuration cannot be changed, so that's why its not saved back.

**Comment by altrisi** [comment]
Why not just make it a regular carpet rule though?

**Comment by gnembon** [comment]
true, it could be just a read only rule so one that cannot be changed in game. That would be safest

**Comment by adryd325** [comment]
How would I make a read only rule, I don't see anything that would specify a rule is read only. Would it be given a Validator that always returns null?

**Comment by gnembon** [comment]
something like that - making sure it can be set on startup

**Pull request closed without merging**
