### PR TITLE
Exceptions - rework

### PR DESCRIPTION
**Pull request by gnembon**
@altrisi your PR is read-only with github, so I needed to make another one. Feel free to compare. Didn't edit the docs yet.

### CODE REVIEW

**Comment by altrisi** [comment]
Any specific reason not to allow custom exception types? I think those were nice for things like libraries, for example, so they could have more specific catch filters. (if it's because of complexity I get it)

As a side note it's a bit sad to have lost the way to throw an error without actually doing something incorrect, but I guess that wasn't really the most important feature of the system.

Also `byId` would probably be a better name for `byValue`, since that now stores by id string.

**Comment by gnembon** [comment]
Yeah, allowing for custom exception types could be useful in libraries, or larger apps, even if its only just one level deeper that the existing hierarchy. I will add it back, just need to make sure its not muddling too much the system. You are correct - simplicity is what I would want to keep here.

For throwing an error that will not get caught, that's what exit is for. What do you think about it?

**Comment by gnembon** [comment]
and yeah, to satisfy https://github.com/gnembon/fabric-carpet/issues/446 stack of `throw` should be accessible in catch statements, maybe as `_stack` or `_trace`.

**Comment by gnembon** [comment]
@altrisi I added the full trace information as you requested, including stack, local peekaboo and pointer to the error in code. I will now add back the ability to through direct children of the build-in exceptions in case programmer wants to distinguish several cases, but that would be limited to only direct children of buit-in exceptions.

**Comment by altrisi** [comment]
Oh, that issue (IIRC, it's a bit old) wasn't about getting the stack programmatically, but about unhandled throw exceptions to show it like regular IEEs, it was when throw just worked as a exit when unhandled.

I guess it's a nice addition anyway, but not sure about where you would use it though.

**Comment by gnembon** [comment]
it woudl be for debugging.

**Pull request merged**
