### PR TITLE
small change. i want to add a function that returns item s rarity

### PR DESCRIPTION
**Pull request by ch-yx**
it s a small change. 
please accept it as soon as possible. XD

### CODE REVIEW

**Review by Ghoulboy78 — APPROVED** [review]
Now all that's missing is the notepad++ suggestions, but looks good otherwise

**Comment by altrisi** [comment]
Question: What is rarity used for?

**Comment by Ghoulboy78** [comment]
Map-making afaik

**Comment by ch-yx** [comment]
> Question: What is rarity used for?

to decide items name 's color in map making.   i sometime hope to print the received item in chat like in vanilla.

**Pull request closed without merging**
