### PR TITLE
Missing semicolon in draw_beta.sc

### PR DESCRIPTION
**Pull request by Ghoulboy78**

### CODE REVIEW

**Comment by Ghoulboy78** [comment]
I'm also gonna take this opportunity to add some explanatory docs to each method in `shapes.scl`, to explain what it does and how it works.

**Comment by altrisi** [comment]
Another thing: `player` should be `player()` in line 55 (or not specifying player in case you want to also give feedback when console does it).

Also I still think global scope should be kept, so the console can use the command (console can't use player scoped commands). At least until something that requires player scope is added.

**Comment by altrisi** [comment]
BTW I found another bug, not sure if you know what causes it: `ball` is not making the same shape as `sphere` (not counting interior ofc):

Sphere:

imagen 
imagen

Ball:

imagen 
imagen

**Comment by Ghoulboy78** [comment]
Actually `draw_sphere `was entirely unaffected by #1052, as along with `draw_diamond`, it doesn't use any calls to `fill_flat` to generate points. However, I am making a pr which fixes this issue, which I noticed when testing #1153.

**Comment by Ghoulboy78** [comment]
I'm not going to change `shapes.scl` in this pr, if I'm already making another pr to fix all the other issues.

**Comment by altrisi** [comment]
Please do the player thing (it throws else) though and consider the scope thing.

**Comment by Ghoulboy78** [comment]
ah ok, I didn't read comment properly, I'll change right now

**Review by gnembon — APPROVED** [review]

**Pull request merged**
