### PR TITLE
just typos

### PR DESCRIPTION
**Pull request by lucifiel1618**

### CODE REVIEW

**Comment by altrisi** [comment]
Full.md is autogenerated from the other two, it doesn't need to be changed.
Also having commas or not is more of a design decision, it works just fine without them.
Only one I see meaningful is disteance, will push that. The one space in a title isn't the only one so I don't think it should be fixed individually.

Thanks for finding it though!

**Comment by lucifiel1618** [comment]
in the example the intended output is `'player at: 567, -2423, 124'`.
You can find commas in it, which is not consistent with the input.
I think you need to either have or remove the commas in both.

**Comment by altrisi** [comment]
Oh true, completely missed that!
Sorry then

**Comment by altrisi** [comment]
Fixed now!

**Pull request closed without merging**
