### PR TITLE
Improve compatibility with other mods by using MixinExtras and reimplementing the shapes compatibility layer

### LINKED ISSUE #1309: Scarpet shapes are back to being incompatible with Canvas
The compatibility layer was commented out.

### PR DESCRIPTION
**Pull request by altrisi**
This PR intends to improve compatibility with other mods _without_ loosing functionality (no "`require = 0` compatibility", this actually removes two of those). This should also fix the worldedit conflict without needing them to disable features with Carpet.

- Adds (and uses it for most things it can be) Mixin Extras (implements #1272)

  Things I didn't change: the ones around movable BEs (just in case), the ones around `CarpetSettings.skipGenerationChecks` (there was a comment somewhere that made me not want to change those), the ones that would slightly decrease performance (such as dispenser qc, given the original expression is evaluated regardless of order)

- Readds the shapes compatibility layer with different rendering engines (Canvas) (fixes #1309)

  It was removed in a (snapshot?) commit, but the issue still occurs without it.

Pending stuff (will do likely tomorrow, feel free to test though):
- ~~Assert the Mixin Extras dependency is bundled for production~~ checked
- Assert it works in production
- Maybe further testing in production? Just in case, idk
- Assert compatibility with removed `require = 0`s is still a thing
  I'll likely need to backport those to test, since these mods aren't in snapshots

### CODE REVIEW

**Comment by gnembon** [comment]
question - why replace all these redirects, only do that for mixins that are questionable?

Scenario - what if suddenly something stop being supported in this external library?

**Comment by altrisi** [comment]
The scenario is already solved by "we bundle the library", so we are in control of the version and loaded classes, and it only depends on Mixin's API, which we already depend on and is unlikely to change (and even if it did, given fabric loader is compatible with all mc versions their fork also ensures compatibility with API changes in Mixin, like it happened during the loader 0.12 update, that the Mixin API behaviour that broke was presented changed only via opt-in).

As to why replace them all? I don't really know, but my intention was to prevent future issues and provide the compatible way directly (you can't really know what other modders will want to do in the future, and many users will just think "it crashes" and remove one of the mods), and in some cases (IMO) having the annotation say exactly what it does makes it easier to read (`WrapWithCondition` vs `Redirect`). It also makes sure that if there's a subtle change in vanilla, those would be caught here too (example a method that called `something(variable)` starts calling `something(variable+2)` wouldn't be updated in Carpet's mixin if using a Redirect, but would with this. Not really sure if that can actually happen, but still).

And because I had some free time with nothing else to do really.

**Comment by gnembon** [comment]
My gut feeling tells me its better to stick to standards and implement 'new shiny things' only where it really matters. 

And with things getting incompatible - its fine. its better to get a bug report and ponder what is the best way to solve it, rather than have a solution that would silently don't work as intended.

**Comment by gnembon** [comment]
Too is great, but its non standard. 

Should only be used in places known for causing compat issues, and only there.

**Comment by altrisi** [comment]
Will close it given it's got full of conflicts, will open a new one if I redo it at some point.

**Pull request closed without merging**
