### PR TITLE
More datapack examples

### LINKED ISSUE #795: [Scarpet Suggestion] create_recipe() and create_loot_table()
`create_recipe(name, content, datapack?, zipped?)`
Add functions to add a new recipe/loot_table with the specified name and content (from a map*).
by default it will be generated in the `script_name` unzipped datapack, but it is possible to change it.

  *example of map:
```sci
{
  'type' -> 'minecraft:smithing',
  'base' -> {
    'item' -> 'minecraft:deepslate_coal_ore'
  },
  'addition' -> {
    'item' -> 'minecraft:stone'
  },
  'result' -> {
    'item' -> 'minecraft:coal_ore'
  }
}
```

### PR DESCRIPTION
**Pull request by BisUmTo**
Added in scapet docs an example for recipes and for loot tables.

Fix #795

### CODE REVIEW

**Comment by BisUmTo** [comment]
Ehm... I attached the "players() TYPO" pool request too... I hope is not a problem

**Review by Firigion — COMMENTED** [review]
While you are fixing stuff here, mind making 'create_datapack()' into `create_datapack()`?

**Comment by BisUmTo** [comment]
? I didn't get it...

**Comment by gnembon** [comment]
I got it - I will fix it on the side.

**Review by gnembon — APPROVED** [review]

**Pull request merged**
