### PR TITLE
Minor corrections to Entities.md

### PR DESCRIPTION
**Pull request by TheCatSaber**
Moved
<pre>
Run(‘/kill ’ + e~'command_name’);
</pre>
To modify(e, ‘kill’) since that makes more sense than it being at query(e, 'persistence').

### CODE REVIEW

**Comment by Ghoulboy78** [comment]
I think it was meant to go into the `query(e,'command_name')` as an example of how that works

**Comment by gnembon** [comment]
yep, that was for the command_name - right above it.

**Comment by TheCatSaber** [comment]
Is that where?

**Comment by Ghoulboy78** [comment]
yes

**Pull request merged**
