### PR TITLE
Adding matrix support to scarpet

### PR DESCRIPTION
**Pull request by Ghoulboy78**
This is gonna be so cool!

### CODE REVIEW

**Comment by James103** [comment]
Can you remove the first two unrelated commits from this PR, leaving just the last two commits?

**Comment by Ghoulboy78** [comment]
oh wow lol i didnt notice them there

**Comment by Ghoulboy78** [comment]
they dont appear to do anything,

**Comment by gnembon** [comment]
dude pls no.
- Think about the big picture, not just 2d arrays: image support, tensor support. 
- Don't spam namespace with single-use functions (identity) - API design needs to survive a few interations of functinonality. Consult with me when I am back or let me start it and continue with extra beef. Not now though.
- in any case, try using libraries - I woudn't use tensorflow right away, but there are a few smaller ones that seem sufficient. If libraries are not adequate - there should be a good reason to reinvent the wheel.

Closing before it starts to grow - but you can keep it in your pocket and we can go back to that later.

**Comment by Ghoulboy78** [comment]
I couldnt find any libraries online tho mate...

**Pull request closed without merging**
