### PR TITLE
Update draw_beta.sc

### LINKED ISSUE #594: Few issues with Scarpet draw and distance apps
List of issues (detailed below):
- [x] [Distance] Lines and labels are too near to the ground
- [ ] [Distance] Right clicks block functionality was changed again after merging
- [ ] [Draw] Update handling may be overcomplicated
- [x] ~[Distance] If lines are enabled, it will draw infinite lines in the same position~ Not Applicable anymore

<details>
<summary> [Distance] Lines and labels are too near the ground</summary>

When using the line functionality in the distance app (mostly with the brown carpet), the label and the line gets inside of the carpet, and it's directly on the floor. This could be solved by drawing the line slightly higher

</details>

### [Distance] Right clicks block was changed back to places block after merging

The `right_clicks_block` event was used instead of the `places_block` due to parity with the Java command. The Java command allows to set positions with the carpet even when the carpet doesn't actually get placed (like right clicking in walls), and that's the reason why it was changed (see https://github.com/gnembon/fabric-carpet/pull/553#discussion_r526396965). It was "reverted" in 4c6d449553fc6fa6d4373a899011fd4d22bf9681

### [Draw] Update handling may be overcomplicated

This was readded right before merging, in 623f9f39e16d77dee0ea1f3994508e2eef4788d3. As already commented in the pull request (and it was removed at that time), updates are already sent from Scarpet's `set` function when `fillUpdates` is true. However, it was added back last minute without a second to comment, overcomplicating both `affected()` and `set_block`, due to adding each pos into a list instead of just adding +1.

The change needed to revert this would basically be about removing the `without_updates` wrap in `set_block`, only adding +1 to global_affected (maybe even remove the `if block != block` since that is already handled by Carpet and do `global_affected += set(...)` since booleans are numbers, or similar), changing `global_affected` to be and be reset to a number again and printing just the variable.

<details>
<summary>[Distance] If lines are enabled, it will draw infinite lines in the same position</summary>

Tired of writing, but this is an important one. See the thing and a sketch for a workaround in https://github.com/gnembon/fabric-carpet/pull/553#discussion_r527476529 (slightly outdated). "Part of the fix" was kind-of added, but the most important part wasn't (not scheduling a new line)

</details>

#### Other small things that may or may not be considerable
- ~[Distance] The label has almost no information (probably still WIP)~
- ~[Distance] The label recalculates the distance every time it's rendered~
- ~[Distance] It's not necessary to check for start when drawing since it will always be present when end is~

### LINKED ISSUE #637: [Suggestion] Abstract core functionality of draw app into a library
With the rise of world editing software since the recent changes in other software, there are suggestions of developing and integrating new methods of doing the same as the `draw` (beta) app inside other, bigger apps.

Therefore, my suggestion here would be to make the draw command app just a wrapper for a more generic library that would contain the shape processing code, that could then also be included in other apps, instead of having duplicated code.

My suggestion would be to separate every shape building method from the app into the library, and then following the next format to be called:

```py
draw_[shape]([...params], set_handler);

//# Example set_handler implementation
set_handler(pos)-> (
    existing = block(pos);
    if (global_block != existing && (!global_replacement || _block_matches(existing, global_replacement) ),
        global_positions += bool(set(existing, global_block))
    )
);

//# Example call
import('shapes','draw_sphere');

global_replacement = 'dirt';
global_block = 'iron_block';
global_positions = 0;

draw_sphere([100,60,100], 25, true, 'set_handler'); //# draw_sphere(pos, radius, hollow, set_handler)
print('Affected '+global_positions+' blocks');
```

Relates to Ghoulboy78/World-edit-scarpet#4

### PR DESCRIPTION
**Pull request by Ghoulboy78**
Fixes #594
Fixes #637 

This is the one which is still WIP, the other ones are ready.

### CODE REVIEW

**Comment by Ghoulboy78** [comment]
>Note: This does NOT resolve #637, since you cannot import() things from (at least unloaded) non-library rule apps (since when can you import from non-libraries btw? Just found it). The idea in that issue was to move those basic functions into another (library) app, with them returning a list to be used in the draw app, and any other app that would need them.

>I would suggest to keep that separate from this PR, since this already has many things needing review in it blocking it from being merged.

>BTW, you forgot to remove the debug timers (the times can already be gotten by executing the functions with /script in [app] run ...)

This is altrisi's last comment in #618, just keeping here so I don't forget

**Comment by Ghoulboy78** [comment]
Btw, does it rly need to be global app? I have it currently as todo decide in the script, cos im kinda unsure...

**Comment by DragonEggBedrockBreaking** [comment]
> This is the one which is still WIP, the other ones are ready.

Isn't that what draft Pull Requests are for?

**Comment by DragonEggBedrockBreaking** [comment]
> > Isn't that what draft Pull Requests are for?
> 
> Yeah, but there wasn't rly much to change, plus I kinda got distracted...

Yeah, makes sense.

**Comment by Ghoulboy78** [comment]
IMO it's done now that Ive upgraded the algorithms to be the most efficient I can make them:

**Comment by Ghoulboy78** [comment]
IMO it's done, now that the algorithms are as efficient as I can make them:
sphere: O(n^2) (100% efficient)
ball: O(n^3) (100% efficient)
diamond (filled) : O(n^3) (as efficient as scarpet makes it, which idk how to calculate, but I doubt that it's 100%)
diamond (hollow) : O(n^2) (A little less than 100% efficient, cos I think I iterate over some points twice, but still lightning fast)
pyramid (filled) : O(n^3) (100% efficient)
pyramid (hollow) : O(n^2), cos the base is also O(n^2) and is kinda separate, so for all intents and purposes it's still O(n^2) (100% efficient)
Same dealio with cones, not bothered to type that much.
cuboids and cylinders are both similar: Filled is O(n^3), and hollow is O(n^2) across the board (the deal wit hthe closed ends of these guys is the same as the base of the pyramids and cones)

**Comment by Ghoulboy78** [comment]
I improved circles by using Bresenham circle algorithm, see here: https://www.javatpoint.com/computer-graphics-bresenhams-circle-algorithm
and for filled I just saw here: https://stackoverflow.com/questions/10878209/midpoint-circle-algorithm-for-filled-circles
and just figured out the theory.
It's cool that I could just copy some c# code, and most of it still worked, just needed some syntax changes!

**Comment by altrisi** [comment]
You need to register the library as a `builtInScript` library in `CarpetScriptServer` for it to be loadable from `assets` (like `math`)

**Comment by Ghoulboy78** [comment]
oye im dum thx for reminding mate

**Comment by altrisi** [comment]
Small mention that `return(what)` can be replaced by just `what` at the end of functions of the library, to avoid those return calls. Should not be that bad given that the most expensive part is probably computing the shape itself, but it's a small optimization that I guess may make things slightly faster at least in small/simple shapes.

Also personal opinion (feel free to not agree with me): I think having to pass the actual arguments instead of a list of the args in specific order is simpler and easier to read/understand.

**Comment by Ghoulboy78** [comment]
hmm, yeah, that is vey true, but I opted for this cos im a lazyboi and it let me jsut do `call(fun, argslist)`. Also, the only difference is literally ad [ and ], so its not a big deal. As for the return thing, I kinda forgot abt it.

**Pull request merged**
