### PR TITLE
Adding system_info('world_min_spawning_light')

### PR DESCRIPTION
**Pull request by Ghoulboy78**
Title says it all. Note that it takes into account modifications fro mdatapacks.

### CODE REVIEW

**Comment by ch-yx** [comment]
Sounds like it's referring to the spawning cap. . . Is it possible to have the word light in the rule name?

**Comment by Ghoulboy78** [comment]
True that

**Comment by Ghoulboy78** [comment]
Should I backport this into 1.18.x? Cos that's the version where you were first able to change this with a datapack, and it may be useful info

**Comment by altrisi** [comment]
Carpet doesn't usually do backports, I don't think it should be tbh, it'd likely not even be released.

**Comment by Ghoulboy78** [comment]
fair enough.

**Comment by Ghoulboy78** [comment]
@altrisi ok, ig this is good to go

**Comment by altrisi** [comment]
Always felt like it has a very long name, that's why I didn't merge it, but given idk how to call it didn't propose anything but wait to see if maybe someone came up with something better.

Feature itself looks good, though don't remember if I tested it.

**Review by altrisi — APPROVED** [review]
Looks good!

What would you think about calling it `world_min_spawning_light` or something like that?

**Comment by Ghoulboy78** [comment]
Yes. I didn't really like this name, thought it was too clunky.

**Pull request merged**
